name: FernGlobalPrefixes
main: com.github.fernthedev.gprefix.spigot.SpigotPlugin
author: Fernthedev
depends:
  - Vault
version: 0.3.0-BETA
website: https://github.com/Fernthedev/global-prefix-approval
api-version: 1.14
commands:
  spigotprefix:
    description: Spigot variant of prefix command
    usage: /sprefix
  sprefix:
    description: Spigot variant of prefix command
    usage: /sprefix
  prefix:
    description: Spigot variant of prefix command
    usage: /prefix